defmodule Bloccs.CompilerTest do
  use ExUnit.Case, async: false

  alias Bloccs.{Parser, Validator, Compiler}

  defp tmp_node(id, in_port, in_schema, out_port, out_schema, impl_mod) do
    """
    [node]
    id = "#{id}"
    version = "0.1.0"
    kind = "transform"

    [ports.in]
    #{in_port} = { schema = "#{in_schema}" }

    [ports.out]
    #{out_port} = { schema = "#{out_schema}" }

    [effects]

    [contract]
    pure_core = "#{impl_mod}.transform/2"
    effect_shell = "#{impl_mod}.execute/2"
    """
  end

  @tag :tmp_dir
  test "emits one source file per node plus a supervisor", %{tmp_dir: tmp} do
    File.write!(Path.join(tmp, "a.bloccs"), tmp_node("a", "i", "X@1", "o", "X@1", "Stub.A"))
    File.write!(Path.join(tmp, "b.bloccs"), tmp_node("b", "i", "X@1", "o", "X@1", "Stub.B"))

    network_path = Path.join(tmp, "net.bloccs")

    File.write!(network_path, ~S"""
    [network]
    id = "compdemo"
    version = "0.1.0"

    [nodes]
    a = { use = "a.bloccs" }
    b = { use = "b.bloccs" }

    [[edges]]
    from = "a.o"
    to   = "b.i"
    """)

    {:ok, network} = Parser.parse_network(network_path)
    :ok = Validator.validate_network(network)

    dest = Path.join(tmp, "out")
    {:ok, %{supervisor: sup, files: files}} = Compiler.compile(network, dest_dir: dest)

    assert sup == Bloccs.Compiled.Compdemo.Supervisor
    assert length(files) == 3
    assert Enum.all?(files, &File.exists?/1)

    assert Enum.any?(files, &(Path.basename(&1) == "a.ex"))
    assert Enum.any?(files, &(Path.basename(&1) == "b.ex"))
    assert Enum.any?(files, &(Path.basename(&1) == "supervisor.ex"))
  end

  @tag :tmp_dir
  test "generated sources include the manifest path as a source comment", %{tmp_dir: tmp} do
    File.write!(Path.join(tmp, "a.bloccs"), tmp_node("a", "i", "X@1", "o", "X@1", "Stub.A"))

    File.write!(Path.join(tmp, "net.bloccs"), ~S"""
    [network]
    id = "tracedemo"
    version = "0.1.0"

    [nodes]
    a = { use = "a.bloccs" }
    """)

    {:ok, network} = Parser.parse_network(Path.join(tmp, "net.bloccs"))
    {:ok, %{files: files}} = Compiler.compile(network, dest_dir: Path.join(tmp, "out"))

    Enum.each(files, fn f ->
      source = File.read!(f)
      assert source =~ "Auto-generated by Bloccs.Compiler"
    end)
  end

  @tag :tmp_dir
  test "supervisor module name is derived from the network id", %{tmp_dir: tmp} do
    File.write!(Path.join(tmp, "a.bloccs"), tmp_node("a", "i", "X@1", "o", "X@1", "Stub.A"))

    File.write!(Path.join(tmp, "net.bloccs"), ~S"""
    [network]
    id = "my_funky_net"
    version = "0.1.0"

    [nodes]
    a = { use = "a.bloccs" }
    """)

    {:ok, network} = Parser.parse_network(Path.join(tmp, "net.bloccs"))

    {:ok, %{supervisor: sup}} = Compiler.compile(network, dest_dir: Path.join(tmp, "out"))
    assert sup == Bloccs.Compiled.MyFunkyNet.Supervisor
  end
end
