defmodule Bloccs.Compiler.Network do
  @moduledoc """
  Emits a Supervisor source file that boots every compiled node pipeline
  and registers the edge table with `Bloccs.Router`.
  """

  alias Bloccs.Manifest.{Network, NetworkNode, Edge}
  alias Bloccs.Compiler

  @doc """
  Compile the network supervisor. Returns the path of the emitted file.
  """
  @spec compile(Network.t(), Path.t()) :: Path.t()
  def compile(%Network{} = network, dest_dir) do
    source = render(network)
    path = Path.join(dest_dir, "supervisor.ex")
    File.write!(path, source)
    path
  end

  @doc "Generated supervisor module name."
  @spec supervisor_module(Network.t()) :: module()
  def supervisor_module(%Network{id: id}) do
    Module.concat([Bloccs.Compiled, Macro.camelize(id), Supervisor])
  end

  defp render(%Network{} = network) do
    sup_module = supervisor_module(network)
    sup = network.supervision

    children =
      network.nodes
      |> Enum.map(fn {_local_id, %NetworkNode{} = nn} ->
        mod = Compiler.Node.module_name(network, nn)
        "{#{inspect(mod)}, []}"
      end)
      |> Enum.join(",\n        ")

    edge_table_literal = render_edge_table(network)

    """
    # Auto-generated by Bloccs.Compiler.Network. Do not edit by hand.
    # Source: #{network.path}
    # Network: #{network.id} v#{network.version}

    defmodule #{inspect(sup_module)} do
      @moduledoc \"\"\"
      Generated Supervisor for the `#{network.id}` network.
      \"\"\"

      use Supervisor

      @network_id #{inspect(String.to_atom(network.id))}
      @edges #{edge_table_literal}

      def start_link(opts \\\\ []) do
        Supervisor.start_link(__MODULE__, opts, name: __MODULE__)
      end

      @impl true
      def init(_opts) do
        :ok = Bloccs.Router.register(@network_id, @edges)

        children = [
          #{children}
        ]

        Supervisor.init(children,
          strategy: #{inspect(sup.strategy)},
          max_restarts: #{sup.max_restarts},
          max_seconds: #{sup.max_seconds}
        )
      end

      @doc "Returns the (network_id, edges) registration data."
      def __bloccs_edges__, do: {@network_id, @edges}
    end
    """
  end

  defp render_edge_table(%Network{edges: edges}) do
    entries =
      Enum.map(edges, fn %Edge{from: from, to: tos} ->
        "{#{inspect(from)}, #{inspect(tos)}}"
      end)

    "[\n        " <> Enum.join(entries, ",\n        ") <> "\n      ]"
  end
end
