defmodule Bloccs.Compiler.Network do
  @moduledoc """
  Emits a Supervisor source file that boots every compiled node pipeline
  and registers the edge table with `Bloccs.Router`.
  """

  alias Bloccs.Manifest.{Network, NetworkNode, Edge}
  alias Bloccs.Compiler

  @doc """
  Compile the network supervisor. Returns the path of the emitted file.
  """
  @spec compile(Network.t(), Path.t()) :: Path.t()
  def compile(%Network{} = network, dest_dir) do
    source = render(network)
    path = Path.join(dest_dir, "supervisor.ex")
    File.write!(path, source)
    path
  end

  @doc "Generated supervisor module name."
  @spec supervisor_module(Network.t()) :: module()
  def supervisor_module(%Network{id: id}) do
    Module.concat([Bloccs.Compiled, Macro.camelize(id), Supervisor])
  end

  defp render(%Network{} = network) do
    sup_module = supervisor_module(network)
    sup = network.supervision

    children =
      network.nodes
      |> Enum.flat_map(fn {_local_id, %NetworkNode{} = nn} ->
        Compiler.Node.pipeline_modules(network, nn)
      end)
      |> Enum.map(&"{#{inspect(&1)}, []}")
      |> Enum.join(",\n        ")

    edge_table_literal = render_edge_table(network)
    join_registrations = render_join_registrations(network)

    """
    # Auto-generated by Bloccs.Compiler.Network. Do not edit by hand.
    # Source: #{network.path}
    # Network: #{network.id} v#{network.version}

    defmodule #{inspect(sup_module)} do
      @moduledoc \"\"\"
      Generated Supervisor for the `#{network.id}` network.
      \"\"\"

      use Supervisor

      @network_id #{inspect(String.to_atom(network.id))}
      @edges #{edge_table_literal}

      def start_link(opts \\\\ []) do
        Supervisor.start_link(__MODULE__, opts, name: __MODULE__)
      end

      @impl true
      def init(_opts) do
        :ok = Bloccs.Router.register(@network_id, @edges)#{join_registrations}

        children = [
          #{children}
        ]

        Supervisor.init(children,
          strategy: #{inspect(sup.strategy)},
          max_restarts: #{sup.max_restarts},
          max_seconds: #{sup.max_seconds}
        )
      end

      @doc "Returns the (network_id, edges) registration data."
      def __bloccs_edges__, do: {@network_id, @edges}
    end
    """
  end

  # Generate a `Bloccs.Join.register/2` call per join node, run at supervisor
  # boot right after the edge table is registered. Empty for networks with no
  # join nodes.
  defp render_join_registrations(%Network{nodes: nodes}) do
    regs =
      nodes
      |> Enum.filter(fn {_id, %NetworkNode{manifest: m}} -> m.join end)
      |> Enum.map(fn {local_id, %NetworkNode{manifest: m}} ->
        j = m.join
        required = m.ports_in |> Map.keys() |> Enum.sort()

        ":ok = Bloccs.Join.register({@network_id, #{inspect(local_id)}}, " <>
          "%{required: MapSet.new(#{inspect(required)}), on: #{inspect(j.on)}, " <>
          "timeout_ms: #{inspect(j.timeout_ms)}, deadletter: #{inspect(j.deadletter)}})"
      end)

    case regs do
      [] -> ""
      _ -> "\n    " <> Enum.join(regs, "\n    ")
    end
  end

  defp render_edge_table(%Network{edges: edges}) do
    entries =
      Enum.map(edges, fn %Edge{from: from, to: tos} ->
        "{#{inspect(from)}, #{inspect(tos)}}"
      end)

    "[\n        " <> Enum.join(entries, ",\n        ") <> "\n      ]"
  end
end
