defmodule Bloccs.Compiler.Node do
  @moduledoc """
  Emits a Broadway pipeline source file for a single network node.

  Produces real `.ex` source on disk (not in-memory `Module.create/3`) so
  stack traces point at debuggable file paths and generated output is
  PR-reviewable — the "legible IR" thesis applied to compilation.
  """

  alias Bloccs.Manifest.{Network, NetworkNode, Node}

  @doc """
  Compile one node. Returns the path of the written file.
  """
  @spec compile(NetworkNode.t(), Network.t(), Path.t()) :: Path.t()
  def compile(%NetworkNode{} = nn, %Network{} = network, dest_dir) do
    source = render(nn, network)
    path = Path.join([dest_dir, "nodes", "#{nn.local_id}.ex"])
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, source)
    path
  end

  @doc "Module name of the compiled pipeline."
  @spec module_name(Network.t(), NetworkNode.t()) :: module()
  def module_name(%Network{id: nid}, %NetworkNode{local_id: lid}) do
    Module.concat([
      Bloccs.Compiled,
      Macro.camelize(nid),
      Macro.camelize(to_string(lid))
    ])
  end

  defp render(%NetworkNode{} = nn, %Network{} = network) do
    %Node{} = manifest = nn.manifest

    pure = manifest.contract.pure_core
    shell = manifest.contract.effect_shell

    pipeline_module = module_name(network, nn)
    pipeline_name = Bloccs.Router.pipeline_name(String.to_atom(network.id), nn.local_id)

    [{in_port, _}] = port_list(manifest.ports_in)
    producer_name = Bloccs.Router.producer_name(String.to_atom(network.id), nn.local_id, in_port)

    concurrency = Map.get(network.deploy.concurrency, nn.local_id, 1)

    """
    # Auto-generated by Bloccs.Compiler.Node. Do not edit by hand.
    # Source manifest: #{manifest.path}
    # Network: #{network.id} v#{network.version}

    defmodule #{inspect(pipeline_module)} do
      @moduledoc \"\"\"
      Generated Broadway pipeline for `#{network.id}.#{nn.local_id}` (from
      `#{manifest.path}`).
      \"\"\"

      use Broadway

      @network_id #{inspect(String.to_atom(network.id))}
      @local_id   #{inspect(nn.local_id)}
      @in_port    #{inspect(in_port)}
      @impl_module #{inspect(manifest_module(pure))}
      @pure_fun    #{inspect(pure.function)}
      @shell_fun   #{inspect(shell.function)}

      def start_link(opts \\\\ []) do
        Broadway.start_link(__MODULE__,
          name: #{inspect(pipeline_name)},
          producer: [
            module: {Bloccs.Producer, [name: #{inspect(producer_name)}]},
            concurrency: 1
          ],
          processors: [default: [concurrency: Keyword.get(opts, :concurrency, #{concurrency})]]
        )
      end

      def child_spec(opts) do
        %{
          id: __MODULE__,
          start: {__MODULE__, :start_link, [opts]},
          type: :supervisor,
          restart: :permanent,
          shutdown: 5000
        }
      end

      @impl Broadway
      def handle_message(_, %Broadway.Message{data: data} = msg, _) do
        manifest = @impl_module.__bloccs_manifest__()

        case Bloccs.Pipeline.validate_inbound(manifest, @in_port, data) do
          :ok ->
            run_node(manifest, data, msg)

          {:error, reason} ->
            Broadway.Message.failed(msg, reason)
        end
      end

      defp run_node(manifest, data, msg) do
        caps = Bloccs.Effects.bind(manifest)
        ctx  = Bloccs.Context.new(effects: caps, received_at: DateTime.utc_now())

        try do
          case apply(@impl_module, @pure_fun, [data, ctx]) do
            {:ok, intermediate} ->
              case apply(@impl_module, @shell_fun, [intermediate, ctx]) do
                {:emit, port, payload} ->
                  Bloccs.Router.dispatch(@network_id, @local_id, port, payload)
                  msg

                {:error, reason} ->
                  Broadway.Message.failed(msg, reason)
              end

            {:error, reason} ->
              Broadway.Message.failed(msg, reason)
          end
        rescue
          e -> Broadway.Message.failed(msg, e)
        end
      end
    end
    """
  end

  defp port_list(map) when map_size(map) == 0, do: [{:default, nil}]
  defp port_list(map), do: Enum.to_list(map)

  defp manifest_module(%{module: mod}), do: mod
end
